name: build

on: [workflow_dispatch, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{matrix.config.os}}-${{matrix.config.cc}}-${{matrix.config.ver}}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
           - { os: ubuntu-latest, cc: gcc, cxx: g++, ver: 7 }
           - { os: ubuntu-latest, cc: gcc, cxx: g++, ver: 8 }
           - { os: ubuntu-latest, cc: gcc, cxx: g++, ver: 9 }
           - { os: ubuntu-latest, cc: gcc, cxx: g++, ver: 10 }
           - { os: ubuntu-latest, cc: clang, cxx: clang++, ver: 8 }
           - { os: ubuntu-latest, cc: clang, cxx: clang++, ver: 9 }
           - { os: ubuntu-latest, cc: clang, cxx: clang++, ver: 10 }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
             sudo apt update
             sudo apt install ${{ matrix.config.cxx }}-${{ matrix.config.ver }} \
                              libboost-dev libboost-thread-dev \
                              libsdl2-dev libvisa-dev libuv1-dev liblibfmt-dev
  
      - name: Run CMake
        working-directory: ${{github.workspace}}
        env:
          CC: ${{ matrix.config.cc }}-${{ matrix.config.ver }}
          CXX: ${{ matrix.config.cxx }}-${{ matrix.config.ver }}
        run: |
             mkdir build
             cd build
             cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  
      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config $BUILD_TYPE
